services:
  - type: web
    name: cryptooracle-backend
    env: python
    plan: free
    region: oregon
    branch: main
    rootDir: backend

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000

    envVars:
      - key: OPENAI_API_KEY
        value: sk-...  # Replace with actual key

      # Optional additional env vars:
      # - key: DB_URL
      #   value: postgres://...

