services:
  - type: web
    name: cryptooracle-backend
    env: python
    plan: free  # change to 'starter' or 'standard' if you want higher performance
    region: oregon
    branch: main
    rootDir: backend

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000

    envVars:
      - key: OPENAI_API_KEY
        value: sk-...

      # Add other secrets below as needed
      # - key: DB_URL
      #   value: postgres://...

