services:
  - type: web
    name: cryptooracle-backend
    env: python
    plan: free  # Upgrade to starter or standard for extra horsepower
    region: oregon
    branch: main
    rootDir: backend

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000

    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}

